name: Notify on PR Move to CIP Columns

on:
  workflow_dispatch:
  project_card:
    types: [moved]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR Info
        run: |
          echo "PR Title: ${{ github.event.project_card.note }}"
          echo "New Column Name: ${{ github.event.project_card.column_name }}"
          echo "PR URL: ${{ github.event.project_card.content_url }}"

      - name: Determine Email Recipient
        id: email_recipient
        run: |
          COLUMN_NAME="${{ github.event.project_card.column_name }}"
          PR_TITLE="${{ github.event.project_card.note }}"
          PR_LINK="${{ github.event.project_card.content_url }}"

          # Set test email
          EMAIL_TO="amartin@linuxfoundation.org"

          # Ensure PR_TITLE is not empty, otherwise use 'Unknown PR'
          if [[ -z "$PR_TITLE" ]]; then
            PR_TITLE="Unknown PR"
          fi

          # Ensure PR_LINK is not empty
          if [[ -z "$PR_LINK" ]]; then
            PR_LINK="No link available"
          fi

          # Set environment variables
          echo "EMAIL_TO=${EMAIL_TO}" >> $GITHUB_ENV
          echo "SUBJECT=${PR_TITLE}" >> $GITHUB_ENV
          echo "BODY=Hello,\n\nWe have created a draft of ${PR_TITLE} that is ready for your discussion.\n\nLink to PR: ${PR_LINK}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "EMAIL_TO: $EMAIL_TO"
          echo "SUBJECT: $SUBJECT"
          echo "BODY: $BODY"

      - name: Send Test Email via SendGrid
        if: env.EMAIL_TO != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: "cips"
          password: ${{ secrets.CIPS }}
          subject: "${{ env.SUBJECT }}"
          body: "${{ env.BODY }}"
          to: "${{ env.EMAIL_TO }}"
          from: "github-bot@sync.global"
