name: Notify on PR Move to CIP Columns

on:
  workflow_dispatch:
  project_card:
    types: [moved]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR Info
        run: |
          PR_TITLE="${{ github.event.project_card.note }}"
          PR_LINK="${{ github.event.project_card.content_url }}"

          # Ensure PR_TITLE and PR_LINK are not empty
          if [[ -z "$PR_TITLE" ]]; then
            PR_TITLE="Unknown PR"
          fi
          if [[ -z "$PR_LINK" ]]; then
            PR_LINK="No link available"
          fi

          # Set GitHub environment variables (for use in later steps)
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_LINK=$PR_LINK" >> $GITHUB_ENV

      - name: Debug Email Content
        run: |
          echo "PR Title: $PR_TITLE"
          echo "PR Link: $PR_LINK"

      - name: Send Email via SendGrid API (cURL)
        run: |
          JSON_DATA=$(jq -n \
            --arg email "amartin@linuxfoundation.org" \
            --arg from "amartin@linuxfoundation.org" \
            --arg subject "$PR_TITLE is in ${{ github.event.project_card.column_name }}" \
            --arg body "Hello,\n\nWe have created a draft of '$PR_TITLE' that is ready for your discussion.\n\nLink to PR: $PR_LINK" \
            '{
              "personalizations": [{
                "to": [{"email": $email}]
              }],
              "from": {"email": $from},
              "subject": $subject,
              "content": [{
                "type": "text/plain",
                "value": $body
              }]
            }' | sed ':a;N;$!ba;s/\n/\\n/g')

          echo "JSON Payload:"
          echo "$JSON_DATA" | jq .

          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data "$JSON_DATA"
